% setTrainLocText  

TrainScreen=struct;

TrainScreen(1).part{1}=['We are going to have you read short lists of words, word by word. '...
    'Sometimes these lists will make a sentence, and at other times they will '...
    'be random word lists. That doesn''t matter to you though.'];

TrainScreen(2).part{1}=['All you have to do is keep in mind for a few seconds the '...
'words that were presented. After a short delay you will be given a test word followed by a "?". '...
'You then have to say whether or not you think that that word was in the list you were just presented. '...
'Press "' SameKey  '" if you think it was in the list, or "' DiffKey '" if you think it was not in the list.'];
TrainScreen(2).part{2}=['\n\n\n\n\n\n\n\n\n\n\nBefore each sentence, fixate your eyes on the + that appears '...
    'in the center of the screen.'];

TrainScreen(3).part{1}='Let''s practice.';
